allow_remote_control socket-only
listen_on unix:/tmp/kitty-split-lab
enabled_layouts splits,fat,grid,horizontal,stack,tall,vertical
map cmd+shift+l combine : next_layout : resize_window reset
shell /bin/zsh
initial_window_width 1200
initial_window_height 800
