#KITTY FONT CONFIGURATION

font_size        14

font_family      JetBrains Mono Nerd font Medium
bold_font        JetBrains Mono Nerd font Bold
italic_font      JetBrains Mono Nerd font Medium Italic
bold_italic_font JetBrains Mono Nerd font Bold Italic

disable_ligatures never

