font_family Hack Nerd Font Mono
bold_font Hack Nerd Font Mono Bold
italic_font Hack Nerd Font Mono Italic
bold_italic_font Hack Nerd Font Bold Italic

font_size 16

background_opacity 0.90
dynamic_background_opacity yes

include kitty-gruvbox-theme/gruvbox_dark_hard.conf

# make env variables red
color0 green

# Terminal bell
enable_audio_bell no

background_tint 1

window_padding_width 0
