font_family JetBrains Mono Medium
#font_family Hack Nerd Font Mono
bold_font auto
italic_font auto 
bold_italic_font auto 

font_size 12

background_opacity 0.90
dynamic_background_opacity yes

#include dracula.conf 
#include onedark/onedark.conf
#include kitty-gruvbox-theme/gruvbox_dark_hard.conf
include nord/nord.conf

# make env variables red
color0 green

# Terminal bell
enable_audio_bell no

#background_tint 1

# Mouse & cursor
cursor_blink_interval     1
cursor_stop_blinking_after 4.0
# one of (block, beam, underline)
cursor_shape underline
mouse_hide_wait 3.0

window_padding_width 8
