add_newline = false

[character]
success_symbol = "[➜](bold green) "

[lua]
format = "via [🌙 $version](bold blue) "

[rust]
format = "via [🦀 $version](bold red) "

[git_branch]
format = "on [$symbol$branch(:$remote_branch)]($style) "
symbol = "🌴 "

[package]
format = "is [$symbol$version]($style) " 
symbol = "📦 "
style = "bold 208"
disabled = true
