add_newline = false

[character]
success_symbol = "[🗡️](bold green)"
error_symbol = "[☠️](bold red)"

[lua]
format = "via [$symbol $version]($style) "
symbol = "🌙" 
style = "bold blue"

[rust]
format = "via [$symbol $version]($style) "
symbol = "🦀"
style = "bold red"

[git_branch]
format = "on [$symbol $branch(:$remote_branch)]($style) "
symbol = "🌴"

[package]
format = "is [$symbol $version]($style) " 
symbol = "📦"
style = "bold 208"
disabled = true
